10:39:57 [32mINFO[0m Deploying local:fastapi-k8s-0
10:39:58 [32mINFO[0m Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
10:40:28 [32mINFO[0m Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
10:40:36 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: missing options: non-optional-int, non-optional-bool, non-optional-string        
10:40:52 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: missing options: non-optional-int, non-optional-bool, non-optional-string        
10:41:08 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: missing options: non-optional-string, non-optional-int        
10:41:38 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:42:09 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:42:39 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:43:09 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:43:39 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:44:10 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:44:40 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:45:10 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:45:40 [32mINFO[0m Waiting for model:
  fastapi-k8s/0 [idle] blocked: database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
10:46:09 [32mINFO[0m Model status:

Model    Controller                Cloud/Region        Version  SLA          Timestamp
testing  github-pr-67728-microk8s  microk8s/localhost  3.6.11   unsupported  10:46:09Z

App             Version  Status   Scale  Charm           Channel  Rev  Address         Exposed  Message
django-k8s               active       1  django-k8s                 0  10.152.183.66   no       
fastapi-k8s              blocked      1  fastapi-k8s                0  10.152.183.132  no       database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
flask-k8s                active       1  flask-k8s                  0  10.152.183.187  no       
postgresql-k8s  14.19    active       1  postgresql-k8s  14/edge  684  10.152.183.226  no       

Unit               Workload  Agent  Address       Ports  Message
django-k8s/0*      active    idle   10.1.110.139         
fastapi-k8s/0*     blocked   idle   10.1.110.142         database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, will retry in next update-status
flask-k8s/0*       active    idle   10.1.110.138         
postgresql-k8s/0*  active    idle   10.1.110.141         Primary

10:46:09 [32mINFO[0m Juju error logs:

unit-flask-k8s-0: 10:36:20 ERROR unit.flask-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
unit-flask-k8s-0: 10:36:20 ERROR unit.flask-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool        
unit-flask-k8s-0: 10:36:22 ERROR unit.flask-k8s/0.juju-log invalid configuration:
- non-optional-bool: Field required
- non-optional-int: Field required
unit-flask-k8s-0: 10:36:22 ERROR unit.flask-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-bool, non-optional-int        
unit-flask-k8s-0: 10:36:23 ERROR unit.flask-k8s/0.juju-log secret-storage:0: invalid configuration:
- non-optional-bool: Field required
- non-optional-int: Field required
unit-flask-k8s-0: 10:36:23 ERROR unit.flask-k8s/0.juju-log secret-storage:0: Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-bool, non-optional-int        
unit-flask-k8s-0: 10:36:39 ERROR unit.flask-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
unit-flask-k8s-0: 10:36:39 ERROR unit.flask-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AppConfig
non_optional_int
  Field required [type=missing, input_value={'non_optional_bool': Tru... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-flask-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int        
unit-django-k8s-0: 10:37:41 ERROR unit.django-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
unit-django-k8s-0: 10:37:41 ERROR unit.django-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool        
unit-django-k8s-0: 10:37:43 ERROR unit.django-k8s/0.juju-log invalid configuration:
- non-optional-bool: Field required
- non-optional-int: Field required
unit-django-k8s-0: 10:37:43 ERROR unit.django-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-bool, non-optional-int        
unit-django-k8s-0: 10:37:44 ERROR unit.django-k8s/0.juju-log secret-storage:4: invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
unit-django-k8s-0: 10:37:44 ERROR unit.django-k8s/0.juju-log secret-storage:4: Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool        
unit-django-k8s-0: 10:38:43 ERROR unit.django-k8s/0.juju-log postgresql:5: invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
unit-django-k8s-0: 10:38:43 ERROR unit.django-k8s/0.juju-log postgresql:5: Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool        
unit-django-k8s-0: 10:39:17 ERROR unit.django-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
unit-django-k8s-0: 10:39:17 ERROR unit.django-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for AppConfig
non_optional_int
  Field required [type=missing, input_value={'non_optional_bool': Tru... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
  File "/var/lib/juju/agents/unit-django-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int        
unit-fastapi-k8s-0: 10:40:11 ERROR unit.fastapi-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
- non-optional-string: Field required
unit-fastapi-k8s-0: 10:40:11 ERROR unit.fastapi-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_string
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool, non-optional-string        
unit-fastapi-k8s-0: 10:40:12 ERROR unit.fastapi-k8s/0.juju-log invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
- non-optional-string: Field required
unit-fastapi-k8s-0: 10:40:12 ERROR unit.fastapi-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_string
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool, non-optional-string        
unit-fastapi-k8s-0: 10:40:15 ERROR unit.fastapi-k8s/0.juju-log postgresql:7: invalid configuration:
- non-optional-string: Field required
- non-optional-bool: Field required
- non-optional-int: Field required
unit-fastapi-k8s-0: 10:40:15 ERROR unit.fastapi-k8s/0.juju-log postgresql:7: Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_string
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-string, non-optional-bool, non-optional-int        
unit-fastapi-k8s-0: 10:40:16 ERROR unit.fastapi-k8s/0.juju-log secret-storage:6: invalid configuration:
- non-optional-int: Field required
- non-optional-bool: Field required
- non-optional-string: Field required
unit-fastapi-k8s-0: 10:40:16 ERROR unit.fastapi-k8s/0.juju-log secret-storage:6: Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for AppConfig
non_optional_bool
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_int
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_string
  Field required [type=missing, input_value={'oidc_redirect_path': '/... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-int, non-optional-bool, non-optional-string        
unit-fastapi-k8s-0: 10:40:52 ERROR unit.fastapi-k8s/0.juju-log invalid configuration:
- non-optional-string: Field required
- non-optional-int: Field required
unit-fastapi-k8s-0: 10:40:52 ERROR unit.fastapi-k8s/0.juju-log Wrong Charm Configuration
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 123, in from_charm
    app_config_class(**user_defined_config)
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AppConfig
non_optional_int
  Field required [type=missing, input_value={'non_optional_bool': Tru... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
non_optional_string
  Field required [type=missing, input_value={'non_optional_bool': Tru... 'openid profile email'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_utils.py", line 59, in wrapper
    instance._create_charm_state()  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm.py", line 686, in _create_charm_state
    return CharmState.from_charm(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/juju/agents/unit-fastapi-k8s-0/charm/venv/paas_charm/charm_state.py", line 127, in from_charm
    raise CharmConfigInvalidError(error_messages.short) from exc
paas_charm.exceptions.CharmConfigInvalidError: missing options: non-optional-string, non-optional-int        
unit-fastapi-k8s-0: 10:41:10 ERROR unit.fastapi-k8s/0.juju-log database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, stdout: , stderr: Traceback (most recent call last):
  File "/usr/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lib/python3.12/site-packages/alembic/config.py", line 1022, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/lib/python3.12/site-packages/alembic/config.py", line 1012, in main
    self.run_cmd(cfg, options)
  File "/lib/python3.12/site-packages/alembic/config.py", line 946, in run_cmd
    fn(
  File "/lib/python3.12/site-packages/alembic/command.py", line 483, in upgrade
    script.run_env()
  File "/lib/python3.12/site-packages/alembic/script/base.py", line 545, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 116, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 136, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/alembic/env.py", line 11, in <module>
    from app import Base, engine
  File "/app/app.py", line 11, in <module>
    from fastapi_mail import ConnectionConfig, FastMail, MessageSchema, MessageType
  File "/lib/python3.12/site-packages/fastapi_mail/__init__.py", line 1, in <module>
    from fastapi_mail.config import ConnectionConfig
  File "/lib/python3.12/site-packages/fastapi_mail/config.py", line 9, in <module>
    class ConnectionConfig(Settings):
  File "/lib/python3.12/site-packages/fastapi_mail/config.py", line 11, in ConnectionConfig
    MAIL_PASSWORD: SecretStr
                   ^^^^^^^^^
NameError: name 'SecretStr' is not defined

unit-fastapi-k8s-0: 10:46:02 ERROR unit.fastapi-k8s/0.juju-log database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, stdout: , stderr: Traceback (most recent call last):
  File "/usr/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lib/python3.12/site-packages/alembic/config.py", line 1022, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/lib/python3.12/site-packages/alembic/config.py", line 1012, in main
    self.run_cmd(cfg, options)
  File "/lib/python3.12/site-packages/alembic/config.py", line 946, in run_cmd
    fn(
  File "/lib/python3.12/site-packages/alembic/command.py", line 483, in upgrade
    script.run_env()
  File "/lib/python3.12/site-packages/alembic/script/base.py", line 545, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 116, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 136, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/alembic/env.py", line 11, in <module>
    from app import Base, engine
  File "/app/app.py", line 11, in <module>
    from fastapi_mail import ConnectionConfig, FastMail, MessageSchema, MessageType
  File "/lib/python3.12/site-packages/fastapi_mail/__init__.py", line 1, in <module>
    from fastapi_mail.config import ConnectionConfig
  File "/lib/python3.12/site-packages/fastapi_mail/config.py", line 9, in <module>
    class ConnectionConfig(Settings):
  File "/lib/python3.12/site-packages/fastapi_mail/config.py", line 11, in ConnectionConfig
    MAIL_PASSWORD: SecretStr
                   ^^^^^^^^^
NameError: name 'SecretStr' is not defined


10:46:09 [32mINFO[0m Forgetting model main...